[package]
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
categories = ["wasm"]
description = "pack up the wasm and publish it to npm!"
documentation = "https://rustwasm.github.io/wasm-pack/"
license = "MIT/Apache-2.0"
name = "wasm-pack"
readme = "README.md"
repository = "https://github.com/ashleygwilliams/wasm-pack.git"
version = "0.5.1"

[dependencies]
atty = "0.2.11"
cargo_metadata = "0.6.0"
console = "0.6.1"
curl = "0.4.13"
dirs = "1.0.4"
failure = "0.1.2"
flate2 = "1.0.2"
hex = "0.3"
human-panic = "1.0.1"
indicatif = "0.9.0"
lazy_static = "1.1.0"
parking_lot = "0.6"
serde = "1.0.74"
serde_derive = "1.0.74"
serde_ignored = "0.0.4"
serde_json = "1.0.26"
siphasher = "0.2.3"
slog = "2.3"
slog-async = "2.3"
slog-term = "2.4"
strsim = "0.8.0"
structopt = "0.2"
tar = "0.4.16"
toml = "0.4"
which = "2.0.0"
zip = "0.4.2"

[dependencies.openssl]
optional = true
version = "0.10.11"

[dev-dependencies]
tempfile = "3"

[features]
vendored-openssl = ["openssl/vendored"]
