[package]
name = "wasm-pack"
description = "📦✨ your favorite rust -> wasm workflow tool!"
version = "0.9.1"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
repository = "https://github.com/ashleygwilliams/wasm-pack.git"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["wasm"]
documentation = "https://rustwasm.github.io/wasm-pack/"

[dependencies]
atty = "0.2.14"
cargo_metadata = "0.12.1"
console = "0.13.0"
dialoguer = "0.7.1"
curl = "0.4.34"
env_logger = { version = "0.8.2", default-features = false }
failure = "0.1.8"
human-panic = "1.0.3"
glob = "0.3.0"
log = "0.4.11"
openssl = { version = "0.10.31", optional = true }
parking_lot = "0.11.1"
reqwest = { version = "0.10.10", features = ["blocking"] }
semver = "0.11.0"
serde = "1.0.118"
serde_derive = "1.0.118"
serde_ignored = "0.1.2"
serde_json = "1.0.60"
strsim = "0.10.0"
siphasher = "0.3.3"
structopt = "0.3.21"
toml = "0.5.7"
which = "4.0.2"
binary-install = "0.0.2"
walkdir = "2.3.1"
chrono = "0.4.19"

[dev-dependencies]
assert_cmd = "1.0.2"
lazy_static = "1.4.0"
predicates = "1.0.5"
serial_test = "0.5.1"
serial_test_derive = "0.5.1"
tempfile = "3.1.0"

[features]
vendored-openssl = ['openssl/vendored']
